import styles from '@/styles/Home.module.css';
import { Container } from '@mui/material';
import { styled } from '@mui/system';
import { Inter } from '@next/font/google';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import signImg from '../assets/pages/home/oscar-sign.png';

const inter = Inter({ subsets: ['latin'] })

const BorderTitle = styled('h1')({
  background: 'linear-gradient(#0b0b0b, #9c9c9c)',
  textFillColor: 'transparent',
  backgroundClip: 'text',
  fontSize: '2.5em',
})

interface HomeProps {

}

const Home: React.FC<HomeProps> = () => {

  return (
    <Container maxWidth="lg">
      <Head>
        <title>DB Compare</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p className={inter.className}>
            Get started by editing&nbsp;
            <code className={styles.code}>src/pages/index.tsx</code>
          </p>
          <div className={inter.className} style={{ display: 'flex', alignItems: 'center' }}>
            By&nbsp;&nbsp;
            <Image
              className={styles.logo}
              src={signImg}
              alt="Sign"
              priority
              width={80}
              height={40}
            />
          </div>
        </div>
        <div className={styles.center}>
          <div className={styles.thirteen}>
            <BorderTitle className={inter.className}>
              DB
            </BorderTitle>
          </div>
          &nbsp;&nbsp;&nbsp;
          <div style={{ display: 'flex', alignItems: 'baseline' }}>
            <h1 className={inter.className} style={{ fontSize: '2em', letterSpacing: '4px' }}>
              COMPARE
            </h1>
            &nbsp;
            <h4 className={inter.className}>
              .JS
            </h4>
          </div>
        </div>
        <div className={styles.grid}>
          <Link
            href="/compare-db-schema"
            className={styles.card}
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Compare Schema <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Obtain the definitions of SP, FN, VIEW, and TABLE of the database, and compare the differences
            </p>
          </Link>
          <a
            className={styles.card}
            rel="noopener noreferrer"
            onClick={() => alert('comming soon')}
          >
            <h2 className={inter.className}>
              Compare Data <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Obtain the specified Table data of the database and compare the data differences
            </p>
          </a>
        </div>
      </main>
    </Container>
  )
}

export default Home;